language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

env:
  - DJANGO="django==1.11"
  - DJANGO="django==1.10.7"
  - DJANGO="django==1.9.13"
  - DJANGO="django==1.8.18"
  - DJANGO="django==2.0"

install:
  - pip install $DJANGO
  - pip install flake8
  - pip install coveralls

before_script:
   flake8 .

script: coverage run --source=menu_generator manage.py test

after_success:
  coveralls